name: Python Build

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar para builds
  pull_request:
    branches:
      - main  # ou a branch que você deseja monitorar para pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Define o sistema operacional para o ambiente de build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Set up Python
      uses: actions/setup-python@v4  # Configura o Python no ambiente
      with:
        python-version: '3.9'  # Defina a versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências do projeto

    - name: Run tests
      run: |
        pytest  # Ou o comando de teste que você utiliza, se for outro

    - name: Build project (opcional)
      run: |
        # Se você tiver um comando para build, como `python setup.py install` ou algo similar
        python setup.py install  # Ajuste conforme a necessidade do seu projeto

    - name: Upload build artifacts (opcional)
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: path/to/your/build/output  # Ajuste o caminho para o que você gera ao buildar