name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar a versão do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Altere conforme sua versão do Python

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
