name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Debug para verificar estrutura do diretório
      - name: Debug file structure
        run: ls -R

      # Passo 3: Configurar a versão do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Altere conforme necessário

      # Passo 4: Instalar dependências
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Passo 5: Executar o script main.py
      - name: Run Python script
        run: |
          python main.py > output.txt

      # Passo 6: Gerar e salvar artefato
      - name: Generate artifact
        run: |
          mkdir -p artifact_output
          mv output.txt artifact_output/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meu-artefato # Nome do artefato no GitHub
          path: artifact_output/ # Caminho para o artefato
